### ISSUE TITLE
Use bleno as ANCS accessories

### ISSUE THREAD

**Issue by desar** [sandeepmistry/node-ancs#3]
Hi Sandeep,

I believe ANCS doesn't dictate anything about GAP role (central or peripheral).

Since node-ancs is using noble instead of bleno, I assume that it work as central role.
In this case you gonna need app on iPhone to work as peripheral. (LightBlue will do).

Now, based on this blog:
http://blog.punchthrough.com/post/63658238857/the-apple-notification-center-service-or-wtf-is
If you can advertise ANCS service solicitation, iPhone can see that advertiser(peripheral)
as accessories. So you don't need any application on iPhone.

I did the following test:
on Linux:
hcitool -i hci0 cmd 0x08 0x0008 1E 02 01 03 11 15 D0 00 2D 12 1E 4B 0F A4 99 4E CE B5 31 F4 05 79 00 00 00 00 00 00 00 00 00 00
*) this will advertise ANCS uuid (7905F431-B5CE-4E99-A40F-4B1E122D00D0) as service solicitation (AD Type: 0x15).

on iPhone:
Open The default Settings>Bluetooth.
After you type the above command on linux you should see the peripheral listed as "Accessories". You can click to do pairing.
*) note that ANCS scanning seem to be in sparse interval that regular scanning (few seconds should do)

My request: 
Also implement ancs with bleno to act as peripheral.

Thanks

**Comment by sander** [comment]
@desar Did you find a way eventually to use ANCS with a Bluez peripheral? I’m trying to get iOS notifications on my Intel Edison board, and as you describe, it currently connects only when a central app is running, and disconnects after several seconds.

**Comment by sandeepmistry** [comment]
@sander you can try out [ancs-test.js](https://github.com/sandeepmistry/bleno/blob/role-reversal/ancs-test.js) in the [```role-reversal``` branch of bleno](https://github.com/sandeepmistry/bleno/tree/role-reversal)

**Comment by robotastic** [comment]
Awesome! @sander, let me know if you get it to work. I have some Arduino
code here that can process the ANCS messages.

https://github.com/robotastic/ANCS-Library

**Comment by sander** [comment]
@sandeepmistry Great, thanks! I’ve had it running on OS X, but on my Edison I get this error:

    # node ancs-test.js
    bleno
    
    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: spawn ENOENT
        at errnoException (child_process.js:1011:11)
        at Process.ChildProcess._handle.onexit (child_process.js:802:34)

I’ve tried after `rfkill unblock bluetooth`, with and without the iPhone `connect`ed in `bluetoothctl`, and with and without `bluetoothd` running. With `bleno.on('error', ...)` there’s no difference. Is there a way to get a better stack trace, or do you already know what this error could be?

**Comment by sander** [comment]
Figured out what that error came from by monkey patching `require('child_process').spawn` and worked around it with `ln -s node_modules/noble/build`. Now the script runs but doesn’t get further than `advertisingStart`. Will try some more things, let me know if you have ideas.

**Comment by desar** [comment]
Just putting some comment here.
This was few months ago, my memory could be wrong. anyway.

>@desar Did you find a way eventually to use ANCS with a Bluez peripheral?
 
@sander, unfortunately not with bluez. If I remember correctly I end up using 
bluegiga dongle with rpi as peripheral for ANCS. Unlike, a normal ble dongle,
bluegiga has usb to serial function, so you will see it as a com port on your host (ex. rpi).
You can almost use any language for BLE gatt programming, since bluegiga
soft on nordic chip will convert serial data to access nordic softdevices.
bluegiga is used in commercial products like myo armband and also lumo lift I guess.
(I bet maintaining different code for both windows and mac is burden for them, 
 and they could also make some profit by selling those dongle too)

Edison is using qualcomm ble chip I guess. Will be nice if bluez working with ANCS.
As central, when connecting to iPhone from bluez, I did try to set the connection
parameter to satisfy Apple Bluetooh Guideline without any success (disconnected 
after few sec). Perhaps, not only connection parameters but some hci command 
sequence that iOS don't like  and decided to close the connection. (Using ble packet 
capture and analyze it might reveal something).
BLE might not need apple MFi, but they sure will collect some consultation fee if 
you go commercial this way....

Only got weekend for hobby, but I might also interested in trying sandeep's ancs-test in bleno.
Hope you got it resolved before that;)
Also the latest bluez (see release note for 5.30) had some improvement for GATT API,
"experimental, support both 'client' and server functionality" so maybe worth checking too. 
(Although you can always grab dev. source, they do release monthly, so 5.31 is imminent)

**Comment by robotastic** [comment]
It worked fine when I tried ants-test.js on OS X. Oddly, I didn’t even need to pair and my macbook didn’t show up under bluetooth devices. I wonder if it is because HandOff was running. 

I couldn’t get it working on Ubuntu though. I comes up fine and I can see the ‘test’ bluetooth id under Device on the iPhone. I can connect, but no ANCS notifications  show up on the ubuntu side.

Has anyone gotten it work on Linux?

This is all I got:

bleno
on -> stateChange: poweredOn
on -> advertisingStart: success

**Comment by sandeepmistry** [comment]
@sander be sure to run ```npm install``` and ```node-gyp rebuild```. The ```*-ble``` binaries from noble are not compatible, bleno has it's own version of those.

**Comment by sander** [comment]
@desar thanks for your comments! Good to know that reliable ANCS is possible with non-Apple clients.

@sandeepmistry thanks, didn’t know about `node-gyp`. I’ve recompiled the bleno binaries and run `ancs-test.js` on OS X and Edison (self-compiled BlueZ 5.30). Got the same issues, but now I’ve kept logs:

[OS X logs](http://s89.nl/tmp/report-osx.tar.gz) (tarball, containing plain text, BTSnoop and PacketLogger formats), procedure:

1. OS X and iPhone were already paired.
2. Start logging with PacketLogger.
3. Start `node ancs-test.js`.
4. Several notifications come in on `stdout`.
5. Stop `node`.
6. Stop logging.

[Edison logs](https://gist.github.com/sander/5d2e2104d45b1da6117f) (`hcidump` and `stdout`, plain text on Gist), procedure:

1. Start Edison. The Edison and iPhone are not paired.
2. `rfkill unblock bluetooth`. Interface `hci0` is up according to `hciconfig`.
3. Start logging with `hcidump`.
4. Start `node ancs-test.js`.
5. On iPhone, go to Settings > Bluetooth, and pair with `edison` under MY DEVICES. After a few seconds, the status changes to Connected.
6. Wait, create some notifications that appear on iPhone. They don’t appear in `stdout` on Edison.
7. After seconds, stop `node`.
8. Stop logging.

I have to stop for now, but maybe the logs can help compare what happens on OS X vs what happens on BlueZ? There seems to be a way to get BT logs from iOS as well, but I didn’t do that yet.

**Comment by sandeepmistry** [comment]
@sander You could try killing ```bluetoothd```, see: https://github.com/sandeepmistry/bleno/issues/24

However, it's needed for pairing security. So, try killing it, starting the bleno app, and they starting bluetoothd.

**Comment by sander** [comment]
@sandeepmistry Thanks, that helped to get pairing to work. Still no notifications however. I’ve followed these steps:

1. Start Edison. Edison and iPhone not paired.
2. `rfkill unblock bluetooth`
3. `killall bluetoothd`
4. Start logging with `hcidump`.
5. Start `DEBUG=* node ancs-test.js`.
6. `hciconfig hci0 up`
7. Pair from iPhone.
8. `systemctl start bluetooth`
9. Create several notifications. They appear on iPhone but not on Edison.

Here are the logs: https://gist.github.com/sander/ce61da9cfb8937dadafb

Any ideas? Is there another way to access ANCS from bluez (5.30, with kernel 3.10) that has been shown to work?

**Comment by sander** [comment]
To answer my last question, I now have a connection that is lasting for at least 5 minutes. Not useful yet, and maybe not news, but it made me happy to see that it is possible with bluez (5.24 again) on Edison. Steps:

0. Run `systemctl stop bluetooth`.
1. Run `hcitool lescan`.
2. Launch an iOS app that advertises a BLE server, such as BLE Utility.
3. From the scan, copy the temporary UUID that matches the iOS app. For example, `5C:71:C9:4D:A5:64`.
4. Run `gatttool -I -b 5C:71:C9:4D:A5:64 -t random`.
5. In the program, run `sec-level high`, `connect`, `characteristics`.
6. From the result, take the value handle from the notification channel, e.g. `0x001e`.
7. Run `char-desc 0x001e`, and take the handle from the characteristic following the notification channel ID, e.g. `0x001f`.
8. Run `char-write-req 0x001f 0100`.
9. Wait for notifications to come in.

**Comment by sandeepmistry** [comment]
@sander I haven't tried with BlueZ 5.x, it works with BlueZ 4.101 on my Raspberry Pi though. Since it's on a branch of bleno, keep in mind it's highly experimental.

Your last comment is operating ANCS in central mode, which is identical to the library in this repo.

**Comment by robotastic** [comment]
How far off is the role-reversal branch of Bleno? Should I try to merge before I try getting ancs-test.js to work?

**Comment by sandeepmistry** [comment]
@robotastic it's pretty far off. However, with the node-bluetooth-hci-socket changes, it should be a much simpler, as everything is HCI socket handle based.

**Comment by robotastic** [comment]
Thanks @sandeepmistry !
What do you think the best way to get ANCS working with the current branch of Bleno? Should I try to reimplement ancs-test.js?

**Comment by sandeepmistry** [comment]
@robotastic I would actually try to do everything but advertising in noble now.

You can report a role reversal "discover" here: https://github.com/sandeepmistry/noble/blob/master/lib/hci-socket/bindings.js#L160 depending on the value of `role`, then store it somewhere. Then stub out the connect method based on the role for that handle.

That's what's in my head currently ...

**Comment by robotastic** [comment]
@sandeepmistry I have tried messing around with this but haven't had much luck. Does this approach seem right?

Start the advertisement using Bleno and the code from ancs-test.js and then listen for a Noble.discover and look at the role to see what the role is.

I am having a problem where noble gets the connect event, but is failing because it doesn't have the peripheral in _peripheral:

on -> stateChange: poweredOn
on -> advertisingStart: error Error: Command Disallowed
noble: unknown peripheral 5a8f5801fc85 connected!
https://github.com/sandeepmistry/noble/blob/master/lib/noble.js#L156

How should I hand off between Bleno and Noble? Should it happen after a particular blend event occurs?

I saw that there is a HCI Event for Role Change:
Role Change -  0x12 - Status, BD_ADDR, New_Role

It doesn't look like that is a defined event. Do you think it would get passed through if I define things out and test for it?

**Comment by robotastic** [comment]
I looked back through the Role Reversal branch and I think I have a little better sense of some of the changes that are needed to Noble. It looks like you need to hook onto the Bleno Accept event and then pass the client address to Noble’s discover event.

 Additional pointers would be great though.
